[package]
name = "python-uiua"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pyuiua"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.21.1"
uiua = "0.11.1"